name: Django CI

on: [ push, pull_request ]

jobs:
  build:
    env:
      POSTGRES_VERSION: 12
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      HTTP_PORT: 8001
      ALLOWED_HOSTS: 127.0.0.1
      SECRET_KEY: t2-r&t0yj0b%q$b^@ptqya=13mq0rsz1_5&h^ub-=+(ueiqsql
      DJANGO_SETTINGS_MODULE: config.settings.docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull Images
      run: |
        docker compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build Containers
      run: |
        docker compose build
    - name: Run Tests
      run: |
        docker compose run web python manage.py test .
    - name: Run Black
      run: |
        docker compose run web python -m black --check .
