name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r nadlogar/requirements/local.txt 
      - run: pip install black isort flake8
      - run: python3 -m black --check .
      - run: python3 -m isort --check .
      - run: flake8
      - run: cd nadlogar && python3 ./manage.py test
